# Generated by Django 4.0.5 on 2022-06-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postage',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privacy',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refunds',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
