# Generated by Django 4.0.5 on 2022-07-01 03:59

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('footer_content', '0003_rename_refunds_returns'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('content', django_quill.fields.QuillField()),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
