# Generated by Django 4.0.5 on 2022-06-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='actioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
