# Generated by Django 4.0.5 on 2022-07-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_deliveryoptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryoptions',
            options={'verbose_name_plural': 'Delivery Options'},
        ),
    ]
