# Generated by Django 4.0.5 on 2022-07-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_deliveryoptions_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryOptions',
        ),
    ]
