# Generated by Django 4.0.5 on 2022-07-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_delete_deliveryoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
