# Generated by Django 4.0.5 on 2022-06-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrationcakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery Images'},
        ),
    ]
