# Generated by Django 4.0.5 on 2022-06-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sub_categories_delete_sub_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_categories',
            options={'verbose_name_plural': 'Sub Categories'},
        ),
    ]
