# Generated by Django 4.0.5 on 2022-06-20 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_sub_categories_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_categories',
            options={'verbose_name_plural': 'Sub-Categories'},
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.sub_categories'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='sub_ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='products.ingredients'),
        ),
    ]
