# Generated by Django 4.0.5 on 2022-06-23 18:40

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_large_sale_price_product_medium_sale_price'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='product',
            name='ingredients',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, db_column='friendly_name', help_text=None, to='products.ingredients'),
        ),
    ]
