# Generated by Django 4.0.5 on 2022-06-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_sub_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name_plural': 'Ingredients'},
        ),
    ]
