# Generated by Django 4.0.5 on 2022-07-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
