# Generated by Django 4.0.5 on 2022-07-06 19:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_remove_product_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Rating',
        ),
    ]
